# Source: cluster-api-aws/templates/machine-pool.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: cpwigb5rf-mp-taco
  namespace: cpwigb5rf
spec:
  clusterName: cpwigb5rf
  replicas: 3
  template:
    metadata:
      labels:
            servicemesh: enabled
            taco-ingress-gateway: enabled
            taco-lma: enabled
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: cpwigb5rf
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: cpwigb5rf-mp-taco
        namespace: cpwigb5rf
      version: v1.22.5

